# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnumber', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to=settings.AUTH_USER_MODEL),
        ),
    ]
